Add word2vec dataset, model, utils
SberProcessMining/Sber_Process_Mining pull request #12
Opened 2021-07-30 15:10 UTC by mrgsv

2021-08-02 06:29 UTC, SberProcessMining requested changes

2021-08-02 06:29 UTC, SberProcessMining commented on requirements.txt
> +sberpm~=1.2.0
Reuqirements file should be tuned - you want scikit-learn and torch to be the latest version, but that seems unnecessary. Also sberpm should not be requirenent for sberpm.

2021-08-02 06:29 UTC, SberProcessMining commented on sberpm/ml/vectorizer/word2vec_utils/word2vec_dataset.py
> +    """Inspired by github.com/goddoe"""
Are there any possible license conflicts?

2021-08-02 07:09 UTC, mrgsv commented on sberpm/ml/vectorizer/word2vec_utils/word2vec_dataset.py
> +    """Inspired by github.com/goddoe"""
There is no LICENSE file in this repo.

2021-08-02 18:24 UTC, SberProcessMining requested changes

2021-08-02 18:24 UTC, SberProcessMining commented on sberpm/ml/vectorizer/word2vec_utils/model.py
> -class SkipGramModel(nn.Module):
Why have you dismissed a skip-gram model?

2021-08-03 10:19 UTC, mrgsv commented on sberpm/ml/vectorizer/word2vec_utils/model.py
> -class SkipGramModel(nn.Module):
I suppose this model is slower than CBOW.

2021-08-03 10:19 UTC, mrgsv commented on requirements.txt
> -torch~=1.9.0
done

2021-08-03 10:41 UTC, SberProcessMining approved these changes

2021-08-10 11:45 UTC, merged